spring:
  config:
    import: optional:configserver:http://config-service:8788
    activate:
      on-profile: docker
---
server:
  port: 0
spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://localhost:8788
